// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Self.Infrastructure.Data;

namespace Self.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190709200512_UserBasedWordBasketsEdit")]
    partial class UserBasedWordBasketsEdit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Self.Core.Entities.BasketAggregate.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OwnerId");

                    b.HasKey("Id");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("Self.Core.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("WordContentId");

                    b.HasKey("Id");

                    b.HasIndex("WordContentId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("Self.Core.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BasketId");

                    b.Property<string>("OriginalWord")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Sentence");

                    b.Property<string>("TranslatedWord")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ViewCount");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("Word");
                });

            modelBuilder.Entity("Self.Core.Entities.Notification", b =>
                {
                    b.HasOne("Self.Core.Entities.Word", "WordContent")
                        .WithMany()
                        .HasForeignKey("WordContentId");
                });

            modelBuilder.Entity("Self.Core.Entities.Word", b =>
                {
                    b.HasOne("Self.Core.Entities.BasketAggregate.Basket")
                        .WithMany("Words")
                        .HasForeignKey("BasketId");
                });
#pragma warning restore 612, 618
        }
    }
}
